#!/usr/bin/env bash
#
# different DM uses different filename:
# lightdm: ~/.xprofile
# slim:    ~/.xinitrc

# from old ~/.xinitrc
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

log () {
  echo "$1=<$2>" >> ~/.xinitrc_LOG
}

init_____xfce () {
  export XIM=fcitx
  export GTK_IM_MODULE=xim
  export QT_IM_MODULE=xim
  export XMODIFIERS=@im=fcitx

  local hostname="$(hostname)"
  if [ "$hostname" = "cosmos" ]; then
    xrandr --output HDMI-0 --set underscan on
  fi

  if [ "$hostname" = "djpon" ] || [ "$hostname" = "cosmos" ] ;then
    setxkbmap jp
  else
    log "not running setxkbmap jp"
  fi

  if [ "$hostname" = "thinkpad" ];then
    synclient TouchPadOff=1 # disable touchpad
  fi

  # fcitx-xkb causes xmodmap settings to be reset
  fcitx -rd # --disable fcitx-xkb

  # no need to run xmodmap.
  # run this for once instead:
  #   $ localectl --no-convert set-x11-keymap us pc104 ,qwerty 'caps:swapescape'
  # xmodmap -e 'clear Lock'
  # xmodmap -e 'keycode 66 = Escape'
  # xmodmap -e 'keycode 9 = Caps_Lock'
  xset r rate 160 40

  # disable pc speaker
  xset -b

  # ssh-agent
  # eval $(ssh-agent -s)

  # enable touch scroll in fx
  export MOZ_USE_XINPUT2=1
}

if [[ -d "$HOME/Android/Sdk" ]]; then
  export ANDROID_HOME="$HOME/Android/Sdk"
fi

init_____xfce
log 'xinitrc' 'running'
unset init_____xfce
unset log
