#!/bin/sh

# Unset session variables to prevent conflicts
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# Ensure proper keyboard and system paths are loaded
[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

# Fix for rendering issues in certain X11 apps
vncconfig -iconic &

# Start the XFCE4 Desktop Environment
exec startxfce4
