transaction_log            /var/log/btrbk.log
snapshot_dir               snapshots

incremental                yes
snapshot_preserve_min      2d
snapshot_preserve          14d
target_preserve_min        no
target_preserve            20d 10w *m
btrfs_commit_delete        each

volume /media/sdcard/
  subvolume live

volume /media/sda
  subvolume k3s-agent
  target /media/sdcard/snapshots
